version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    interval: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: favicons-webpack-plugin
    versions:
    - 5.0.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
