name: build
on:
  push:
    branches:
      - '*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  run-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: expenses-client-testing:latest
      - 
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: expenses-client-testing:latest
          shell: sh 
          run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
      -
        name: Set up production Docker Buildx
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Build production container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/expenses-client:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [setup, run-tests]
    if: github.ref == 'refs/heads/master'
    steps:
      -
        name: Set up production Docker Buildx
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push production container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/expenses-client:latest
